### ISSUE TITLE
没有kernel的配置文件

### ISSUE THREAD

**Issue by zx121122** [mitwo-dev/android_kernel_xiaomi_msm8960#1]
没有kernel的配置文件。不知道编译kernel时使用什么配置文件，难道是msm8960-perf_defconfig或msm9615_defconfig？

**Comment by M1cha** [comment]
atm this repository is a pure CAF kernel without support for aries.
It will take some time for Ivan to add support for it because he started from scratch to make it more stable.

**Comment by zx121122** [comment]
thanks for your answer

**Comment by M1cha** [comment]
it has been updated now :)
